name: Python Selenium Tests

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with your desired Python version, e.g., '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Chrome browser
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 5: Run Selenium tests
      - name: Run Selenium tests
        env:
          DISPLAY: ":99" # Necessary for headless mode
        run: |
          pytest # Runs all tests in headless mode based on the configuration in your test code

      # Step 6: Upload any test results or screenshots if tests fail
      - name: Upload screenshots (if tests fail)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: selenium-screenshots # Name for the uploaded artifact
          path: ./screenshots # Replace with the directory where screenshots are saved
